# @package _global_

stage: 2

model:
  lr: ${optimizer.bridge_lr}
  dropout: 0.15
  grad_clip: 1.0
  temperature: 0.07
  embed_dim: 768
  max_length: 64
  eval_config: /workspace/AskVideos-VideoCLIP/eval_configs/video_clip_v0.1.yaml

optimizer:
  bridge_lr: 2e-5
  llm_lr: 2e-6
  video_lr: 1e-6
  weight_decay: 0.01
  warmup_ratio: 0.04
  training_ratio: 1.0

trainer:
  max_epochs: 50
  gpus: 4
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  logger_name: stage2
  log_dir: ${project_root}/scripts/yoloworld_lightning/logs/msrvtt
  precision: 16-mixed
  gradient_clip: 1.0
  log_every_n_steps: 100
